(ns astrogator.poetry.lines)

(defrecord Line [text tags])

(def first-lines
  [(->Line "A distant (star|sun) (glims|glows|shines)" [:single])
   (->Line "Eternal (twilight|sunset)" [:single])
   (->Line "Neverending (days|light)" [:multiple :bright])
   (->Line "Two distant (stars|suns) (glim|glow|shine)" [:multiple])
   (->Line "(Stars|Suns) dancing above" [:multiple])
   (->Line "A (bright|white) (scorching|burning) sky" [:molten :bright])
   (->Line "A (scorching|flaming) giant (star|sun)" [:bright])
   (->Line "A (hail|rain) of embers" [:molten :hostile])
   (->Line "(Infinite|Eternal) darkness" [:frozen :hostile :dark])
   (->Line "(Mountains|Towers) of (black|gray|dark) clouds" [])
   (->Line "(Distant|Lonely|Struggling) rays of light" [])
   (->Line "Spores (travel|conquer) the skies" [:habitable])
   (->Line "A faint (smell|taste) of life" [:habitable])
   (->Line "A (hint|trace) of (air|O2)" [:habitable])
   (->Line "Ashes levitate" [:dry])

   (->Line "(Clouds|Mists) arise up high" [])
   (->Line "(Clouds|Mists) (refract|reflect) bright light" [])
   ;(->Line "Black dust bowls roam here" [:dry])
   (->Line "(Bleak|Yellow) streaks of clouds" [:dry])
   ])

(def second-lines
  [(->Line "on (dark|black) obsidian plains." [:hostile])
   (->Line "a cathedral of (dark|black) (rock|glass)." [:hostile])
   (->Line "(dark|black) (spikes|spears|swords) of (solid|frozen) basalt." [:hostile])
   (->Line "thunder on (waves|dunes) of (lava|magma)." [:molten :hostile])
   (->Line "rivers of (creeping|flowing|glowing) metal." [:molten :hostile])
   (->Line "a (place|land) (swallowing|consuming) itself." [:molten :hostile])
   (->Line "a cathedral of (dead|white) ice." [:frozen :hostile])
   (->Line "(glimmering|shimmering) through icy winds." [:frozen])
   (->Line "fountains of steam fight the cold." [:frozen])
   (->Line "a wreckage (eaten|crushed) by glaciers." [:frozen])
   (->Line "white crystals (slicing|cutting) the sky." [:frozen])
   (->Line "for endless silicon dunes." [:dry])
   (->Line "(wastes|plains) of neverending (salt|ash|sand)." [:dry])
   (->Line "fractal (splinters|flowers) of (white|bleak) (salt|dust)." [:dry])
   (->Line "an ocean without limits." [:wet])
   (->Line "and a sea without a shore." [:wet])
   (->Line "fragile (leaves|green) on spiky rocks" [:habitable :frozen])
   (->Line "(spots|specks) of (life|light) beneath the waves." [:habitable :wet])
   (->Line "whales climb (dunes|mountains) of water." [:habitable :wet])
   (->Line "Shapes of wings against the sky." [:habitable])

   (->Line "cool dew mottling the surface." [:habitable])
   (->Line "above silent fungus trees." [:habitable])
   (->Line "(titan|giant) (reptiles|insects) (hunt|seek) for (meat|food)." [:habitable])
   (->Line "a restless (whirl|swirl) of red dust." [:dry :hostile])
   (->Line "ever-moving foam afloat." [:wet])
   (->Line "(freak|strange) sounds echo like bird's song." [])
   (->Line "(pearls|gems|pebbles) washed ashore, smooth sheen." [:wet])
   (->Line "a forest (below|beneath) the (sea|waves)." [:wet :habitable])
   (->Line "corals pulsate in (blue|cold) light." [:wet :habitable])
   (->Line "rain falls soft, so soft on skin." [:habitable :wet])
   ])

(def third-lines
  [(->Line "No place for a man." [:hostile])
   (->Line "We won't stay for long." [:hostile])
   (->Line "Recall our hubris!" [:hostile])
   (->Line "Does this world feel hate?" [:hostile])
   (->Line "Everlasting peace." [:frozen :hostile])
   (->Line "(Embrace|Enjoy) the silence." [:frozen :hostile])
   (->Line "A (bleak|grim) (sanctuary|monument)." [:hostile :dark])
   (->Line "A (grim|dead) universe." [:frozen :hostile :dark])
   (->Line "Let us die in peace." [:hostile :frozen :dark])
   (->Line "A place to take in." [])
   (->Line "Witness the beauty." [])
   (->Line "Entropy's harvest." [:molten])
   (->Line "(See|Heed) the (Majesty|Artistry)." [])
   (->Line "Echoes of life past." [])
   (->Line "And just us to see." [])
   (->Line "What is it's purpose?" [])
   (->Line "We will see the sights." [])
   (->Line "A (last|lost) oasis." [:habitable])
   (->Line "A garden to be." [:habitable])
   (->Line "Memories of (home|earth)." [:habitable])
   (->Line "Life will find a way." [:habitable])
   (->Line "Take a precious breath." [:habitable])
   (->Line "Let's make it our (home|own)." [:habitable])
   (->Line "We will never leave." [:habitable])
   (->Line "A soothing reward." [:habitable])
   (->Line "Does this world feel love?" [:habitable])
   ])
